# Generated by Django 2.1.5 on 2019-01-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeCoune',
            new_name='LikeCount',
        ),
    ]
